#!/usr/bin/env bash
DOTFILES_ROOT=$(pwd)

# From https://github.com/holman/dotfiles/blob/master/script/bootstrap

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
}

link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

get_package_control () {
    info 'Installing Package Control for Sublime Text'
    wget https://packagecontrol.io/Package%20Control.sublime-package
    mv "Package Control.sublime-package" "$sublime_dir/Installed Packages"
}

install_sublime () {
  info 'installing sublime'
  echo ''

  sublime_dir=$HOME/.config/sublime-text-3
  sublime_pkg=$sublime_dir/Packages

  if [ ! -d $sublime_pkg ]
  then
    sudo add-apt-repository ppa:webupd8team/sublime-text-3 -y > /dev/null 2>&1
    sudo apt-get update > /dev/null 2>&1
    sudo apt-get install sublime-text-installer -y > /dev/null 2>&1
    success Installed Sublime Text 3
  fi

  if [ ! -f "$sublime_dir/Installed Packages/Package Control.sublime-package" ]
  then
    get_package_control
    success Installed Package Control for ST3
  fi

  local overwrite_all=false backup_all=false skip_all=false

  for location in sublime/*/ ; do
    base=${location%/}
      base=$(basename $base)
      src="$DOTFILES_ROOT/$location"
      dest="$sublime_pkg/$base"
      link_file "$src" "$dest"
  done
}


setup_gitconfig () {
  if ! [ -f git/gitconfig.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.symlink.example > git/gitconfig.symlink

    success 'gitconfig'
  fi
}

install_dotfiles
# install_sublime
setup_gitconfig

echo ''
echo '  All installed!'
