#!/usr/bin/env bash
#
# Run all dotfiles installers.
DOTFILES_ROOT=$(pwd)

set -e

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

quiet=false
FLAG=$1
if [[ $FLAG = "-y" ]]; then
  quiet=true
  action=y
fi
# find the installers and run them iteratively
for installer in $(find . -name install.sh)
do
  if [[ $quiet = "false" ]]; then
    user "Do you want to install $installer? [y/n]"
    read -n 1 action
    echo ''
  fi
  if [[ "$action" = y ]]; then
    sh -c "${installer}"
    success "Installed $installer"
  fi
done

