#!/usr/bin/env bash
#
# Run all dotfiles installers.
DOTFILES_ROOT=$(pwd)

set -e

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

# find the installers and run them iteratively
for installer in $(find . -name install.sh)
do
  user "Do you want to install $installer? [y/n]"
  read -n 1 action
  echo ''
  if [[ "$action" = y ]]; then
    sh -c "${installer}"
    success "Installed $installer"
  fi
done

